### ISSUE TITLE
Node js i npm

### ISSUE THREAD

**Issue by Ferniss** [rts-cmk-wuhf02/praktikperiode-newsbox-Ferniss#1]
Need to install the framework and gulp with node js

**Comment by BenjiCS** [comment]
You can see this video from Brian Emilius he made tutorial on Gulp 
.Link {
https://www.youtube.com/watch?v=fHobPT-UMkk&list=PLX4-t8Zdi_Xq4tyk4Z0JtPxBEQNBFDM8n
}
